# Generated by Django 4.1.1 on 2022-09-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_shooting_location',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
