# Generated by Django 4.1.1 on 2022-09-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_photo_shooting_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_shooting_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
