# Generated by Django 4.1.1 on 2022-09-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_date_of_birth_alter_pet_name'),
        ('photos', '0006_alter_photo_date_of_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='tagged_pets',
            field=models.ManyToManyField(blank=True, null=True, to='pets.pet', verbose_name='Tag Pets'),
        ),
    ]
