# Generated by Django 4.1.1 on 2022-09-16 13:17

from django.db import migrations, models
import petstagram.photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_photo_photo_shooting_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_file',
            field=models.ImageField(upload_to='images/', validators=[petstagram.photos.validators.validate_file_size], verbose_name='Pet Photo'),
        ),
    ]
