# Generated by Django 4.1.1 on 2022-10-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_date_of_birth_alter_pet_name'),
        ('photos', '0008_alter_photo_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='tagged_pets',
            field=models.ManyToManyField(blank=True, to='pets.pet', verbose_name='Tag Pets'),
        ),
    ]
