# Generated by Django 4.1.1 on 2022-09-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(blank=True, default='https://cdn-icons-png.flaticon.com/512/1077/1077114.png', null=True),
        ),
    ]
