# Generated by Django 4.1.1 on 2022-09-07 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_file', models.ImageField(upload_to='images/')),
                ('description', models.TextField(max_length=300)),
                ('likes', models.IntegerField(default=0, editable=False)),
                ('date_time_of_publication', models.DateTimeField(auto_now_add=True)),
                ('tagged_pets', models.ManyToManyField(to='pets.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=300)),
                ('created_or_edited_on', models.DateTimeField(auto_now=True)),
                ('to_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_templates-.photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'ordering': ['created_or_edited_on'],
            },
        ),
    ]
