# Generated by Django 4.0.1 on 2022-03-10 12:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import petstagram.main_app.custom_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog'), ('bunny', 'Bunny'), ('parrot', 'Parrot'), ('fish', 'Fish'), ('other', 'Other')], max_length=30)),
                ('birthday', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), petstagram.main_app.custom_validators.only_letters_validator])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), petstagram.main_app.custom_validators.only_letters_validator])),
                ('profile_picture', models.URLField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), (None, 'Do not show')], max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/', validators=[petstagram.main_app.custom_validators.validate_image])),
                ('description', models.TextField(blank=True, null=True)),
                ('date_time_of_publication', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0, editable=False)),
                ('pet', models.ManyToManyField(to='restapp.Pet')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='profile',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='restapp.profile'),
        ),
        migrations.AddConstraint(
            model_name='pet',
            constraint=models.UniqueConstraint(fields=('profile', 'name'), name='unique name'),
        ),
    ]
